# Generated by Django 5.2.9 on 2025-12-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_feedback_comment_attendancesession_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnnouncementReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_read_statuses', to='core.announcement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_read_statuses', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Announcement Read Status',
                'verbose_name_plural': 'Student Announcement Read Statuses',
                'unique_together': {('student', 'announcement')},
            },
        ),
        migrations.CreateModel(
            name='StudentAssignmentReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_read_statuses', to='core.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_read_statuses', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Assignment Read Status',
                'verbose_name_plural': 'Student Assignment Read Statuses',
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
