# Generated by Django 5.2.9 on 2026-01-10 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attendancesession_passcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Day Name')),
                ('abbreviation', models.CharField(max_length=3, verbose_name='Abbreviation')),
                ('order', models.IntegerField(unique=True, verbose_name='Day Order')),
            ],
            options={
                'verbose_name': 'Day of Week',
                'verbose_name_plural': 'Days of Week',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Grade Type Name')),
                ('weight', models.FloatField(default=1.0, help_text='Weight for grade calculation', verbose_name='Weight')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Type',
                'verbose_name_plural': 'Grade Types',
                'ordering': ['display_order'],
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.teacher', verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(blank=True, default='', help_text="e.g., 'Monday, Wednesday, Friday'", max_length=50, verbose_name='Day of the Week'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(verbose_name='Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.enrollment', verbose_name='Enrollment')),
                ('grade_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gradetype', verbose_name='Grade Type')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['grade_type__display_order'],
                'unique_together': {('enrollment', 'grade_type')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dayofweek', verbose_name='Day of Week')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='core.schedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Schedule Day',
                'verbose_name_plural': 'Schedule Days',
                'ordering': ['day__order'],
                'unique_together': {('schedule', 'day')},
            },
        ),
    ]
