# Generated by Django 5.2.10 on 2026-01-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_dayofweek_gradetype_alter_feedback_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM core_attendance; DELETE FROM core_assignmentsubmission; DELETE FROM core_enrollment; DELETE FROM core_feedback; DELETE FROM core_studentannouncementreadstatus; DELETE FROM core_studentassignmentreadstatus; UPDATE core_clazz SET teacher_id=NULL, staff_id=NULL;"
        ),
        migrations.RemoveField(
            model_name='scheduleday',
            name='day',
        ),

        migrations.RemoveField(
            model_name='grade',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade_type',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='clazz',
        ),
        migrations.RemoveField(
            model_name='scheduleday',
            name='schedule',
        ),

        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentannouncementreadstatus',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentassignmentreadstatus',
            name='student',
        ),

        migrations.RemoveField(
            model_name='studentannouncementreadstatus',
            name='announcement',
        ),

        migrations.RemoveField(
            model_name='studentassignmentreadstatus',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='teacher',
        ),
        migrations.AddField(
            model_name='clazz',
            name='day_of_week',
            field=models.CharField(blank=True, help_text="e.g., 'Monday, Wednesday'", max_length=100, null=True, verbose_name='Days of Week'),
        ),
        migrations.AddField(
            model_name='clazz',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='clazz',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='final_test',
            field=models.FloatField(blank=True, null=True, verbose_name='Final Test'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='midterm',
            field=models.FloatField(blank=True, null=True, verbose_name='Midterm'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='minitest1',
            field=models.FloatField(blank=True, null=True, verbose_name='Mini Test 1'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='minitest2',
            field=models.FloatField(blank=True, null=True, verbose_name='Mini Test 2'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='minitest3',
            field=models.FloatField(blank=True, null=True, verbose_name='Mini Test 3'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='minitest4',
            field=models.FloatField(blank=True, null=True, verbose_name='Mini Test 4'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('staff', 'Staff')], max_length=20, verbose_name='Role')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualification')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='ContentReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('announcement', 'Announcement'), ('assignment', 'Assignment')], max_length=20, verbose_name='Content Type')),
                ('content_id', models.IntegerField(verbose_name='Content ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('content_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.person', verbose_name='Student/Person')),
            ],
            options={
                'verbose_name': 'Content Read Status',
                'verbose_name_plural': 'Content Read Statuses',
                'unique_together': {('person', 'content_type', 'content_id')},
            },
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.person', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='clazz',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_managed', to='core.person', verbose_name='Assigned Staff'),
        ),
        migrations.AlterField(
            model_name='clazz',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to='core.person', verbose_name='Assigned Teacher'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.person', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.person', verbose_name='Student'),
        ),
        migrations.DeleteModel(
            name='DayOfWeek',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='GradeType',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleDay',
        ),
        migrations.DeleteModel(
            name='StudentAnnouncementReadStatus',
        ),
        migrations.DeleteModel(
            name='StudentAssignmentReadStatus',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
